version: '3.8'
services:
  hashing:
    build:
      context: .
      dockerfile: cmd/hashing/Dockerfile
    ports:
      - "50052:50052"

  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - hashing
