version: '3.8'
services:
  hashing:
    build:
      context: ./hashing
      dockerfile: cmd/Dockerfile
    ports:
      - "50052:50052"

  gateway:
    build:
      context: ./gateway
      dockerfile: cmd/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - hashing
